name: knowledge_app
description: Knowledge OS mobile client (MVP)
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  record: ^5.2.0
  path_provider: ^2.1.2
  receive_sharing_intent: ^1.5.0
  flutter_local_notifications: ^17.2.2

dependency_overrides:
  record_platform_interface: 1.2.0

flutter:
  uses-material-design: true
